import{sha256}from"./digest.js";import{createAssemblyRepository}from"./repository.js";import{assessReadiness}from"./readiness.js";import{success,failure}from"./result-envelope.js";
const id=p=>`${p}_${globalThis.crypto?.randomUUID?.()??`${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}`}`;
export function createAssemblyEngine(options={}){const repository=options.repository??createAssemblyRepository();const createId=options.createId??id;const emit=options.emit??(async()=>success());const now=options.now??(()=>new Date());const evidenceRegistry=options.evidenceRegistry,goalRegistry=options.goalRegistry,triggerRegistry=options.triggerRegistry,problemEngine=options.problemEngine;
 function boundaryCheck(decisionCase,context){if(!decisionCase?.decisionId||!decisionCase?.security?.accessProof?.allowed)return failure("ADI_ASSEMBLY_CASE_UNSECURED","A secured DecisionCase is required.");if(!context?.contextId||context.decisionId!==decisionCase.decisionId||context.tenantId!==decisionCase.tenantId||context.businessId!==decisionCase.businessId)return failure("ADI_ASSEMBLY_CONTEXT_MISMATCH","DecisionContextEnvelope boundary does not match.");if(context.accessDecisionId!==decisionCase.security.accessProof.accessDecisionId)return failure("ADI_ASSEMBLY_ACCESS_MISMATCH","Context authorization does not match the DecisionCase.");return success({tenantId:decisionCase.tenantId,businessId:decisionCase.businessId,decisionId:decisionCase.decisionId})}
 async function assemble(input={}){const decisionCase=input.decisionCase,context=input.contextEnvelope;const boundary=boundaryCheck(decisionCase,context);if(!boundary.ok)return boundary;const q=boundary.data;
  const evidence=evidenceRegistry?.list(q)?.data??[];const goals=(decisionCase.goalIds??[]).map(goalId=>goalRegistry?.get({...q,goalId})).filter(x=>x?.ok).map(x=>x.data);const triggers=(decisionCase.triggerIds??[]).map(triggerId=>triggerRegistry?.get({...q,triggerId})).filter(x=>x?.ok).map(x=>x.data);let problems=(decisionCase.problemIds??[]).map(problemId=>problemEngine?.get({...q,problemId})).filter(x=>x?.ok).map(x=>x.data);if(!problems.length&&problemEngine)problems=problemEngine.list({...q,status:"open"}).data;
  const verificationFailures=[];for(const record of evidence){const verified=await evidenceRegistry.verify({...q,evidenceId:record.evidenceId});if(!verified.ok||!verified.data.valid)verificationFailures.push(record.evidenceId)}
  const readiness=assessReadiness({context,evidence,goals,triggers,problems,verificationFailures,requiredSourceTypes:input.requiredSourceTypes??[]});const assembledAt=now().toISOString();const digestInput={decisionId:q.decisionId,contextId:context.contextId,evidence:evidence.map(x=>[x.evidenceId,x.contentHash]),goals:goals.map(x=>[x.goalId,x.version]),triggers:triggers.map(x=>[x.triggerId,x.version]),problems:problems.map(x=>[x.problemId,x.version]),readiness};let digest;try{digest=await sha256(digestInput)}catch(error){return failure("ADI_ASSEMBLY_DIGEST_FAILED","Assembly digest could not be generated.",{message:error.message})}
  const record=Object.freeze({assemblyId:input.assemblyId??createId("assembly"),tenantId:q.tenantId,businessId:q.businessId,decisionId:q.decisionId,accessDecisionId:context.accessDecisionId,contextId:context.contextId,contextSummary:Object.freeze({fragmentIds:Object.freeze(context.fragments.map(x=>x.fragmentId)),sourceTypes:Object.freeze([...new Set(context.fragments.map(x=>x.sourceType))]),quality:context.quality,conflictCount:context.conflicts?.length??0,missingSourceTypes:Object.freeze([...(context.missingSourceTypes??[])])}),evidenceRefs:Object.freeze(evidence.map(x=>Object.freeze({evidenceId:x.evidenceId,contentHash:x.contentHash,quality:x.quality,freshness:x.freshness}))),goalRefs:Object.freeze(goals.map(x=>Object.freeze({goalId:x.goalId,version:x.version,progressPercent:x.progressPercent}))),triggerRefs:Object.freeze(triggers.map(x=>Object.freeze({triggerId:x.triggerId,version:x.version,severity:x.severity,status:x.status}))),problemRefs:Object.freeze(problems.map(x=>Object.freeze({problemId:x.problemId,version:x.version,urgency:x.urgency,status:x.status}))),verificationFailures:Object.freeze(verificationFailures),readiness,assemblyDigest:digest,digestAlgorithm:"SHA-256",status:readiness.status,version:1,assembledAt,updatedAt:assembledAt,schemaVersion:"1.0.0"});if(!repository.append(record))return failure("ADI_ASSEMBLY_VERSION_CONFLICT","Assembly could not be stored.");await emit("adi.analysis_case.assembled",{assemblyId:record.assemblyId,decisionId:record.decisionId,status:record.status,digest:record.assemblyDigest},q);return success(record)}
 function get(q){const r=repository.get(q);return r?success(r):failure("ADI_ASSEMBLY_NOT_FOUND","Assembly was not found inside the requested boundary.")}function list(q){return success(repository.list(q))}function history(q){return success(repository.history(q))}
 async function verify(q){const found=get(q);if(!found.ok)return found;const r=found.data;const digestInput={decisionId:r.decisionId,contextId:r.contextId,evidence:r.evidenceRefs.map(x=>[x.evidenceId,x.contentHash]),goals:r.goalRefs.map(x=>[x.goalId,x.version]),triggers:r.triggerRefs.map(x=>[x.triggerId,x.version]),problems:r.problemRefs.map(x=>[x.problemId,x.version]),readiness:r.readiness};const actual=await sha256(digestInput);return success({assemblyId:r.assemblyId,valid:actual===r.assemblyDigest,expectedDigest:r.assemblyDigest,actualDigest:actual})}
 return Object.freeze({blockId:"ADI-11",version:"1.0.0",assemble,get,list,history,verify})}
