-- INFINICUS ENGINE — D1 Schema
-- Run once: wrangler d1 execute INFINICUS_DB --file=schema.sql
-- Or paste into the Cloudflare D1 console SQL editor.

-- ── businesses ────────────────────────────────────────────────────────────────
-- One row per user-owned business. Ties all events to an owner + industry.

CREATE TABLE IF NOT EXISTS businesses (
  id          TEXT    PRIMARY KEY,          -- UUID, generated by the API
  user_email  TEXT    NOT NULL,             -- owner (matches KV user:<email>)
  name        TEXT    NOT NULL,
  industry    TEXT    NOT NULL,             -- e.g. 'food', 'tech', 'retail'
  created_at  INTEGER NOT NULL DEFAULT (unixepoch() * 1000),  -- ms epoch
  updated_at  INTEGER NOT NULL DEFAULT (unixepoch() * 1000)
);

CREATE INDEX IF NOT EXISTS idx_businesses_user_email ON businesses (user_email);

-- ── business_events ───────────────────────────────────────────────────────────
-- Append-only event stream. Five event types:
--   sale         — revenue event           (amount, quantity, customer_id?)
--   expense      — cost event              (amount, category)
--   inventory    — stock movement          (item, quantity_delta, unit_cost?)
--   customer     — CRM event               (customer_id, action: new|return|churn)
--   team         — staff event             (member_id, action: hire|fire|review, hours?)

CREATE TABLE IF NOT EXISTS business_events (
  id           TEXT    PRIMARY KEY,          -- UUID
  business_id  TEXT    NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  event_type   TEXT    NOT NULL CHECK(event_type IN ('sale','expense','inventory','customer','team')),
  amount       REAL,                         -- USD value (sale revenue, expense cost, unit cost)
  quantity     REAL,                         -- units sold, stock delta, hours worked
  category     TEXT,                         -- expense category, inventory item name
  customer_id  TEXT,                         -- for sale / customer events
  member_id    TEXT,                         -- for team events
  action       TEXT,                         -- sub-type: 'new','return','churn','hire','fire','review'
  notes        TEXT,                         -- free text
  created_at   INTEGER NOT NULL DEFAULT (unixepoch() * 1000)  -- ms epoch, queryable range
);

-- Covering index for the most common query pattern:
--   SELECT ... WHERE business_id = ? AND created_at BETWEEN ? AND ?
CREATE INDEX IF NOT EXISTS idx_events_business_time
  ON business_events (business_id, created_at);

-- Optional: filter by event type within a business
CREATE INDEX IF NOT EXISTS idx_events_business_type
  ON business_events (business_id, event_type);
