import{PROBLEM_STATUSES,PROBLEM_URGENCIES,PROBLEM_SOURCES,TRANSITIONS}from"./constants.js";import{createProblemRepository}from"./repository.js";import{success,failure}from"./result-envelope.js";
const id=p=>`${p}_${globalThis.crypto?.randomUUID?.()??`${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}`}`;const text=v=>typeof v==="string"?v.trim():"";const textList=v=>Array.isArray(v)?v.map(text).filter(Boolean):typeof v==="string"?v.split(/\r?\n/).map(text).filter(Boolean):[];
function validate(input,update=false){const errors=[];if(!text(input.tenantId))errors.push("tenant_id_required");if(!text(input.businessId))errors.push("business_id_required");if(!update&&text(input.title).length<3)errors.push("title_required");if(!update&&text(input.statement).length<20)errors.push("statement_too_short");if(!update&&text(input.desiredOutcome).length<10)errors.push("desired_outcome_required");if(input.urgency&&!PROBLEM_URGENCIES.includes(input.urgency))errors.push("urgency_invalid");if(input.status&&!PROBLEM_STATUSES.includes(input.status))errors.push("status_invalid");if(input.source&&!PROBLEM_SOURCES.includes(input.source))errors.push("source_invalid");if(input.decisionDeadline&&Number.isNaN(Date.parse(input.decisionDeadline)))errors.push("decision_deadline_invalid");return errors}

export function createProblemDefinitionEngine(options={}){const repository=options.repository??createProblemRepository();const createId=options.createId??id;const emit=options.emit??(async()=>success());const now=options.now??(()=>new Date());const resolveGoal=options.resolveGoal,resolveTrigger=options.resolveTrigger,resolveEvidence=options.resolveEvidence;
 async function validateReferences(input){const errors=[];if(input.goalId&&resolveGoal){const r=await resolveGoal({goalId:input.goalId,tenantId:input.tenantId,businessId:input.businessId});if(!r?.ok)errors.push("goal_reference_invalid")}
  for(const triggerId of input.triggerIds??(input.triggerId?[input.triggerId]:[])){if(resolveTrigger){const r=await resolveTrigger({triggerId,tenantId:input.tenantId,businessId:input.businessId});if(!r?.ok)errors.push(`trigger_reference_invalid:${triggerId}`)}}
  for(const evidenceId of input.evidenceIds??[]){if(resolveEvidence){const r=await resolveEvidence({evidenceId,tenantId:input.tenantId,businessId:input.businessId,decisionId:input.decisionId});if(!r?.ok)errors.push(`evidence_reference_invalid:${evidenceId}`)}}return errors}
 async function create(input={}){const errors=validate(input);errors.push(...await validateReferences(input));if(errors.length)return failure("ADI_PROBLEM_INVALID","Problem definition failed validation.",{errors});if(input.idempotencyKey){const existing=repository.keyGet({tenantId:input.tenantId,businessId:input.businessId,key:input.idempotencyKey});if(existing)return get({problemId:existing,tenantId:input.tenantId,businessId:input.businessId})}
  const framedAt=now().toISOString();const record=Object.freeze({problemId:input.problemId??createId("problem"),tenantId:input.tenantId,businessId:input.businessId,decisionId:input.decisionId??null,goalId:input.goalId??null,triggerId:input.triggerId??input.triggerIds?.[0]??null,triggerIds:Object.freeze([...(input.triggerIds??(input.triggerId?[input.triggerId]:[]))]),evidenceIds:Object.freeze([...(input.evidenceIds??[])]),title:text(input.title),statement:text(input.statement),decisionQuestion:text(input.decisionQuestion),desiredOutcome:text(input.desiredOutcome),scope:text(input.scope),constraints:Object.freeze(textList(input.constraints)),successCriteria:Object.freeze(textList(input.successCriteria)),assumptions:Object.freeze(textList(input.assumptions)),symptoms:Object.freeze(textList(input.symptoms)),exclusions:Object.freeze(textList(input.exclusions)),rootCauseHypotheses:Object.freeze(textList(input.rootCauseHypotheses)),urgency:input.urgency??"medium",status:input.status??"open",source:input.source??"manual",decisionDeadline:input.decisionDeadline??null,framedBy:input.framedBy??null,framedAt,version:1,createdAt:framedAt,updatedAt:framedAt,schemaVersion:"1.0.0"});if(!repository.create(record))return failure("ADI_PROBLEM_DUPLICATE_ID","Problem ID already exists.");repository.keySet({tenantId:record.tenantId,businessId:record.businessId,key:input.idempotencyKey,problemId:record.problemId});await emit("adi.problem.created",record,{tenantId:record.tenantId,businessId:record.businessId,decisionId:record.decisionId});return success(record)}
 function get(q){const r=repository.get(q);return r?success(r):failure("ADI_PROBLEM_NOT_FOUND","Problem was not found inside the requested boundary.")}function list(q){return success(repository.list(q))}function history(q){return success(repository.history(q))}
 async function update(input={}){const found=get(input);if(!found.ok)return found;const candidate={...found.data};for(const field of["title","statement","decisionQuestion","desiredOutcome","scope","constraints","successCriteria","assumptions","symptoms","exclusions","rootCauseHypotheses","urgency","decisionDeadline","goalId","triggerId","triggerIds","evidenceIds"]){if(input[field]!==undefined)candidate[field]=["constraints","successCriteria","assumptions","symptoms","exclusions","rootCauseHypotheses"].includes(field)?Object.freeze(textList(input[field])):["triggerIds","evidenceIds"].includes(field)?Object.freeze([...input[field]]):input[field]}candidate.triggerIds=candidate.triggerIds??(candidate.triggerId?[candidate.triggerId]:[]);const errors=validate({...candidate,tenantId:found.data.tenantId,businessId:found.data.businessId},true);errors.push(...await validateReferences(candidate));if(errors.length)return failure("ADI_PROBLEM_INVALID","Problem update failed validation.",{errors});candidate.version=found.data.version+1;candidate.updatedAt=now().toISOString();const record=Object.freeze(candidate);if(!repository.append(record))return failure("ADI_PROBLEM_VERSION_CONFLICT","Problem version could not be appended.");await emit("adi.problem.updated",{problemId:record.problemId,version:record.version},{tenantId:record.tenantId,businessId:record.businessId,decisionId:record.decisionId});return success(record)}
 async function setStatus(input={}){const found=get(input);if(!found.ok)return found;if(!PROBLEM_STATUSES.includes(input.status)||!TRANSITIONS[found.data.status]?.includes(input.status))return failure("ADI_PROBLEM_TRANSITION_INVALID",`Cannot transition ${found.data.status} to ${input.status}.`);const record=Object.freeze({...found.data,status:input.status,resolution:input.status==="resolved"?text(input.resolution):found.data.resolution??null,version:found.data.version+1,updatedAt:now().toISOString()});if(!repository.append(record))return failure("ADI_PROBLEM_VERSION_CONFLICT","Problem version could not be appended.");await emit("adi.problem.status.updated",{problemId:record.problemId,status:record.status,version:record.version},{tenantId:record.tenantId,businessId:record.businessId,decisionId:record.decisionId});return success(record)}
 async function importLegacy(input){return create({...input,tenantId:input.tenantId,triggerIds:input.triggerId?[input.triggerId]:[],source:PROBLEM_SOURCES.includes(input.source)?input.source:"manual"})}function exportLegacy(q){const found=get(q);if(!found.ok)return found;const x=found.data;return success({problemId:x.problemId,businessId:x.businessId,goalId:x.goalId,triggerId:x.triggerId,title:x.title,statement:x.statement,desiredOutcome:x.desiredOutcome,scope:x.scope,constraints:[...x.constraints],successCriteria:[...x.successCriteria],assumptions:[...x.assumptions],urgency:x.urgency,status:x.status,framedAt:x.framedAt,source:x.source,version:x.version})}
 return Object.freeze({blockId:"ADI-10",version:"1.0.0",create,get,list,history,update,setStatus,importLegacy,exportLegacy})}
