import test from"node:test";import assert from"node:assert/strict";import{createDecisionContextEngine}from"../src/index.js";
const decisionCase={decisionId:"decision_001",tenantId:"tenant_001",businessId:"business_001",traceId:"trace_001",security:{accessDecisionId:"access_001"}};const accessDecision={accessDecisionId:"access_001",allowed:true,decisionId:"decision_001",tenantId:"tenant_001",businessId:"business_001"};
const fragment={recordId:"record_001",tenantId:"tenant_001",businessId:"business_001",sourceType:"business_intelligence",scope:"customer",quality:"verified",observedAt:"2026-07-17T00:00:00Z",schemaVersion:"1.0.0",data:{churnRate:.18},units:{churnRate:"ratio"}};

test("rejects an unsecured DecisionCase",async()=>{const engine=createDecisionContextEngine();const result=await engine.acquire({decisionCase:{...decisionCase,security:null},accessDecision});assert.equal(result.error.code,"ADI_CONTEXT_CASE_UNSECURED")});
test("rejects a mismatched AccessDecision",async()=>{const engine=createDecisionContextEngine();const result=await engine.acquire({decisionCase,accessDecision:{...accessDecision,businessId:"business_002"}});assert.equal(result.error.code,"ADI_CONTEXT_BOUNDARY_MISMATCH")});
test("acquires and normalizes authorized context",async()=>{const engine=createDecisionContextEngine({now:()=>new Date("2026-07-18T00:00:00Z")});engine.providers.register({providerId:"bi",sourceType:"business_intelligence"},{acquire:async()=>[fragment]});const result=await engine.acquire({decisionCase,accessDecision,requiredSourceTypes:["business_intelligence"]});assert.equal(result.ok,true);assert.equal(result.data.fragments.length,1);assert.equal(result.data.fragments[0].provenance.transformation,"structural_normalization_only");assert.equal(result.data.quality.score,100)});
test("accepts the immutable access proof carried by a secured DecisionCase",async()=>{const engine=createDecisionContextEngine();engine.providers.register({providerId:"bi",sourceType:"business_intelligence"},{acquire:async()=>[fragment]});const secured={...decisionCase,security:{...decisionCase.security,accessProof:accessDecision}};const result=await engine.acquire({decisionCase:secured});assert.equal(result.ok,true);assert.equal(result.data.accessDecisionId,"access_001")});
test("isolates provider failure and returns partial context",async()=>{const engine=createDecisionContextEngine();engine.providers.register({providerId:"broken",sourceType:"business_intelligence"},{acquire:async()=>{throw new Error("offline")}});const result=await engine.acquire({decisionCase,accessDecision});assert.equal(result.ok,true);assert.equal(result.meta.partial,true);assert.equal(result.data.providerFailures.length,1)});
test("rejects cross-business provider fragments",async()=>{const engine=createDecisionContextEngine();engine.providers.register({providerId:"bi",sourceType:"business_intelligence"},{acquire:async()=>[{...fragment,businessId:"business_002"}]});const result=await engine.acquire({decisionCase,accessDecision});assert.equal(result.data.fragments.length,0);assert.equal(result.data.invalidFragments[0].errors.includes("business_boundary_mismatch"),true)});
test("detects conflicting scalar values without choosing one",async()=>{const engine=createDecisionContextEngine();engine.providers.register({providerId:"bi",sourceType:"business_intelligence"},{acquire:async()=>[fragment,{...fragment,recordId:"record_002",data:{churnRate:.22}}]});const result=await engine.acquire({decisionCase,accessDecision});assert.equal(result.data.conflicts.length,1);assert.equal(result.data.fragments.length,2)});
